"""Env bridge: drives the headless game from Python, one decision at a time.

Up to this point every episode was generated by a policy written in C# (random or greedy).
Training needs the *network* to choose, and the network lives here -- so the game process
connects back over TCP and asks for an action at each decision point.

One game process is one env; throughput scales by running several (`VecSpireEnv`).

    with SpireEnv(character="IRONCLAD") as env:
        for obs, legal in env:
            env.act(policy(obs, legal))
"""

from __future__ import annotations

import json
import os
import socket
import subprocess
import sys
from dataclasses import dataclass, field

DEFAULT_GAME = os.path.expanduser(
    "~/.local/share/Steam/steamapps/common/Slay the Spire 2")


@dataclass
class EpisodeResult:
    ep: int
    outcome: str
    won: bool
    reward: float
    turns: int
    steps: int
    hp_start: int
    hp_end: int


class SpireEnv:
    """One headless game process, driven decision by decision."""

    def __init__(self, character="IRONCLAD", episodes=100, seed="ALPHASLAYER1",
                 ascension=0, port=0, game_dir=DEFAULT_GAME, fixed_fps=5000,
                 exclude_encounters=None, inject_cards=None, extra_args=(),
                 quiet=True):
        self.character = character
        self.episodes = episodes
        self._srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._srv.bind(("127.0.0.1", port))
        self._srv.listen(1)
        self.port = self._srv.getsockname()[1]

        args = [
            os.path.join(game_dir, "SlayTheSpire2"), "--headless",
            "--fixed-fps", str(fixed_fps),
            "--probe=serve", "--probe-out=/tmp/alphaslayer_probe", "--probe-quit",
            f"--probe-port={self.port}",
            f"--probe-episodes={episodes}",
            f"--probe-character={character}",
            f"--probe-seed={seed}",
            f"--probe-ascension={ascension}",
        ]
        if exclude_encounters:
            args.append(f"--probe-exclude-encounters={','.join(exclude_encounters)}")
        if inject_cards:
            args.append(f"--probe-inject-cards={','.join(inject_cards)}")
        args += list(extra_args)

        env = dict(os.environ, SteamAppId="2868840", SteamGameId="2868840")
        self.proc = subprocess.Popen(
            args, cwd=game_dir, env=env,
            stdout=subprocess.DEVNULL if quiet else None,
            stderr=subprocess.DEVNULL if quiet else None)

        self._srv.settimeout(120)
        self.conn, _ = self._srv.accept()
        self.conn.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        self._f = self.conn.makefile("rw", encoding="utf-8", newline="\n")

        hello = json.loads(self._f.readline())
        assert hello["t"] == "hello", hello
        self.sizes = hello
        self.results: list[EpisodeResult] = []
        self._pending = None
        self._done = False

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()

    def __iter__(self):
        while True:
            step = self.next_decision()
            if step is None:
                return
            yield step

    def next_decision(self):
        """Returns (obs, legal) for the next decision, or None when the run is finished.

        Terminal records are consumed transparently and appended to ``results``.
        """
        while not self._done:
            line = self._f.readline()
            if not line:
                self._done = True
                return None
            msg = json.loads(line)
            t = msg["t"]
            if t == "decision":
                self._pending = msg
                return msg["obs"], msg["legal"]
            if t == "terminal":
                self.results.append(EpisodeResult(
                    msg["ep"], msg["outcome"], msg["won"], msg["reward"],
                    msg["turns"], msg["steps"], msg["hp_start"], msg["hp_end"]))
                continue
            if t == "done":
                self._done = True
                return None
        return None

    def act(self, action_index: int) -> None:
        if self._pending is None:
            raise RuntimeError("act() without a pending decision")
        self._pending = None
        self._f.write(json.dumps({"a": int(action_index)}) + "\n")
        self._f.flush()

    @property
    def win_rate(self) -> float:
        return (sum(r.won for r in self.results) / len(self.results)
                if self.results else 0.0)

    def close(self):
        for fn in (lambda: self._f.close(), lambda: self.conn.close(),
                   lambda: self._srv.close()):
            try:
                fn()
            except Exception:
                pass
        try:
            self.proc.wait(timeout=20)
        except Exception:
            self.proc.kill()


class ResilientSpireEnv:
    """A SpireEnv that survives the game process crashing.

    Long training runs must not lose an episode budget because one env process died. Defect
    still segfaults intermittently (see probe/README.md), and even for stable characters a
    multi-hour run should not be one crash away from losing its rollouts.

    Restarts transparently and continues until ``episodes`` have COMPLETED. The episode in
    flight when a crash happens is discarded, not half-counted -- a truncated episode has no
    terminal record and would poison the value target.

    Exposes the same (obs, legal) / act() loop as SpireEnv.
    """

    def __init__(self, episodes=100, max_restarts=200, seed="ALPHASLAYER1", **kw):
        self.target = episodes
        self.max_restarts = max_restarts
        self.kw = dict(kw)
        self.seed = seed
        self.results: list[EpisodeResult] = []
        self.restarts = 0
        self.discarded = 0
        self._env = None
        self._pending_act = False

    def _spawn(self):
        remaining = self.target - len(self.results)
        # Vary the seed per process so restarts do not replay the identical failing episode.
        self._env = SpireEnv(episodes=max(1, remaining),
                             seed=f"{self.seed}{self.restarts}" if self.restarts else self.seed,
                             **self.kw)
        self._base = len(self.results)

    def __enter__(self):
        self._spawn()
        return self

    def __exit__(self, *exc):
        self.close()

    def __iter__(self):
        while len(self.results) < self.target:
            if self._env is None:
                if self.restarts >= self.max_restarts:
                    return
                self.restarts += 1
                self._spawn()
            try:
                step = self._env.next_decision()
            except Exception:
                step = None
            if step is None:
                # Either the process finished its budget, or it died. Harvest what completed.
                new = self._env.results[self._base - self._base:]
                for r in new:
                    if len(self.results) < self.target:
                        self.results.append(r)
                if self._pending_act:
                    self.discarded += 1
                    self._pending_act = False
                self._env.close()
                self._env = None
                continue
            self._pending_act = True
            yield step

    def act(self, a):
        self._pending_act = False
        try:
            self._env.act(a)
        except Exception:
            # Process died mid-decision; the loop will notice and restart.
            self._env = None

    @property
    def win_rate(self) -> float:
        return (sum(r.won for r in self.results) / len(self.results)
                if self.results else 0.0)

    @property
    def sizes(self):
        return self._env.sizes if self._env else {}

    def close(self):
        if self._env:
            self._env.close()
            self._env = None
