using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions;
using MegaCrit.Sts2.Core.Runs;

namespace AlphaSlayer.Probe;

/// <summary>
/// Env server: hands each decision to an external policy over TCP and applies the reply.
///
/// This is what makes RL possible - up to now every episode was generated by a policy written
/// in C# (random or greedy). Training needs the NETWORK to choose, and the network lives in
/// Python.
///
/// TCP rather than stdio because Godot writes freely to stdout; a dedicated socket keeps the
/// protocol clean. One process is one env, so throughput scales by running several.
///
/// Protocol - newline-delimited JSON, request/response:
///   -> {"t":"decision","ep":N,"step":N,"obs":{...},"legal":[...]}
///   &lt;- {"a":INDEX}
///   -> {"t":"terminal","ep":N,"outcome":"...","won":bool,"reward":F,"turns":N,"hp_end":N}
///   -> {"t":"done","episodes":N,"steps":N}
/// </summary>
public static class Serve
{
    public static async Task RunAsync()
    {
        var host = Probe.ArgValue("probe-host") ?? "127.0.0.1";
        var port = Probe.ArgInt("probe-port", 5555);
        var n = Probe.ArgInt("probe-episodes", 100);
        var turnCap = Probe.ArgInt("probe-turn-cap", 50);
        var ascension = Probe.ArgInt("probe-ascension", 0);
        var seed = Probe.ArgValue("probe-seed") ?? "ALPHASLAYER1";

        Vocab.Build();

        using var client = new TcpClient();
        // Nagle batches small writes and interacts with delayed ACK to add ~40ms per
        // request/response round trip - which caps a decision-per-round-trip protocol at
        // ~20 steps/s no matter how fast the engine or the policy is.
        client.NoDelay = true;
        await client.ConnectAsync(host, port);
        client.NoDelay = true;
        using var stream = client.GetStream();
        using var reader = new StreamReader(stream, Encoding.UTF8);
        using var writer = new StreamWriter(stream, new UTF8Encoding(false)) { AutoFlush = true };
        Probe.Log($"serve: connected to {host}:{port}");

        var harness = new CombatHarness();
        await harness.StartRunAsync(seed, ascension, Probe.ArgValue("probe-character"));
        CardSelect.Install();
        // Potions in COMBAT-ONLY training, opt-in via --probe-potions.
        //
        // This env never opened the potion gate, so use_potion never appeared in combat
        // training -- yet RunServe opens it for every fight in a run. The combat policy was
        // therefore handed an action type it had never seen, for items it could not observe,
        // and drank 28% of the time one was available (~3.8 potions per run, on a 3-slot
        // belt). Training with the gate open is what makes that action mean something.
        // HasFlag, not ArgValue: ArgValue only resolves --key=value (or --key followed by a
        // non-flag token), so a bare trailing --probe-potions silently read as null and the
        // gate stayed shut. The potions were granted and marked usable, and every slot came
        // back gated:true, with use_potion never entering the legal set.
        if (Probe.HasFlag("probe-potions")) Potions.SetGate(null);
        else Potions.ClearGate();
        // Separate RNG for encounter sampling so the mix is reproducible per seed and does
        // not perturb the game's own streams.
        var encRng = new Random(Probe.ArgInt("probe-policy-seed", 12345) ^ Probe.StableHash(seed));

        // Tell the policy what vocabulary this build uses, so it can size its tables.
        await writer.WriteLineAsync(Probe.ToJsonCompact(new Dictionary<string, object>
        {
            ["t"] = "hello",
            ["character"] = harness.Character.Id.Entry,
            ["encounters"] = harness.Encounters.Count,
            ["cards"] = Vocab.Cards.Count + 1,
            ["relics"] = Vocab.Relics.Count + 1,
            ["powers"] = Vocab.Powers.Count + 1,
            ["monsters"] = Vocab.Monsters.Count + 1,
            ["enchantments"] = Vocab.Enchantments.Count + 1,
            ["potions"] = Vocab.Potions.Count + 1,
            ["afflictions"] = Vocab.Afflictions.Count + 1, ["orbs"] = Vocab.Orbs.Count + 1, ["encounter_vocab"] = Vocab.Encounters.Count + 1,
        }));

        long steps = 0;
        var outcomes = new Dictionary<string, int>();
        var sw = Stopwatch.StartNew();

        var potionRng = new Random(Probe.ArgInt("probe-policy-seed", 11) ^ Probe.StableHash(seed));
        for (var ep = 0; ep < n; ep++)
        {
                        await harness.RerollDeckAsync();
            // Restock BEFORE each fight, so every episode is a fresh chance to learn potion
            // usage rather than only the first one.
            if (Probe.HasFlag("probe-potions"))
            {
                var got = Potions.RefillBelt(harness.Player, potionRng);
                if (ep == 0) Probe.Log($"  potion belt refilled: +{got} " +
                                       $"(now {harness.Player.Potions?.Count() ?? 0})");
            }
            var enc = await harness.BeginCombatAsync(harness.NextEncounter(ep, encRng));
            var startHp = harness.Player.Creature.CurrentHp;
            int turns = 0, stepInEp = 0;
            string outcome = null;

            while (turns < turnCap && outcome == null)
            {
                outcome = await Episodes.WaitForDecisionPublic(harness);
                if (outcome != null) break;

                var combat = harness.State;
                var legal = Obs.LegalActions(harness.Player, combat);
                if (legal.Count == 0) { outcome = "no_legal_actions"; break; }

                await writer.WriteLineAsync(Probe.ToJsonCompact(new Dictionary<string, object>
                {
                    ["t"] = "decision",
                    ["ep"] = ep,
                    ["step"] = stepInEp++,
                    ["encounter"] = enc.Id.Entry,
                    ["obs"] = Obs.Extract(harness.Player, combat),
                    ["legal"] = legal.Select(a => (object)a.ToDict()).ToArray(),
                }));

                var reply = await reader.ReadLineAsync();
                if (reply == null) { outcome = "policy_disconnected"; break; }
                var idx = ParseAction(reply, legal.Count);
                var choice = legal[idx];
                steps++;

                if (choice.Kind == "select_card" || choice.Kind == "select_done")
                {
                    var pend = CardSelect.Pending;
                    if (choice.Kind == "select_done") pend?.Finish(); else pend?.Pick(choice.Card);
                    CardSelect.ClearRaised();
                    await CombatHarness.Suspend();
                }
                else if (choice.Kind == "end_turn")
                {
                    var expect = harness.Player.PlayerCombatState.TurnNumber + 1;
                    CombatManager.Instance.SetReadyToEndTurn(harness.Player, false, null);
                    turns++;
                    outcome = await Episodes.WaitForTurnPublic(harness, expect);
                }
                else if (choice.Kind == "use_potion")
                {
                    // Potions are NOT cards: they go through EnqueueManualUse, exactly as
                    // RunServe does. Falling through to PlayCardAction below built an action
                    // with a null card, which hung the episode -- opening the gate here
                    // without this branch made every potion the policy chose a dead end.
                    choice.Potion.EnqueueManualUse(choice.Target);
                    await Episodes.WaitForQueueOrSelectionPublic();
                }
                else
                {
                    RunManager.Instance.ActionQueueSet.EnqueueWithoutSynchronizing(
                        new PlayCardAction(choice.Card, choice.Target));
                    await Episodes.WaitForQueueOrSelectionPublic();
                }
            }

            outcome ??= "turn_cap";
            var won = outcome == "enemies_cleared";
            outcomes[outcome] = outcomes.GetValueOrDefault(outcome) + 1;
            await writer.WriteLineAsync(Probe.ToJsonCompact(new Dictionary<string, object>
            {
                ["t"] = "terminal", ["ep"] = ep, ["outcome"] = outcome, ["won"] = won,
                ["reward"] = won ? 1.0 : 0.0, ["turns"] = turns, ["steps"] = stepInEp,
                ["hp_start"] = startHp, ["hp_end"] = harness.Player.Creature.CurrentHp,
            }));

            CardSelect.Reset();
            await harness.EndCombatAsync(healToFull: true);
            if (outcome == "policy_disconnected") break;
        }

        sw.Stop();
        await writer.WriteLineAsync(Probe.ToJsonCompact(new Dictionary<string, object>
        {
            ["t"] = "done", ["episodes"] = n, ["steps"] = steps,
            ["wall_s"] = sw.Elapsed.TotalSeconds,
        }));

        Probe.Report["serve"] = new Dictionary<string, object>
        {
            ["episodes"] = n, ["steps"] = steps, ["wall_s"] = sw.Elapsed.TotalSeconds,
            ["steps_per_s"] = sw.Elapsed.TotalSeconds > 0 ? steps / sw.Elapsed.TotalSeconds : 0,
            ["outcomes"] = outcomes.ToDictionary(k => k.Key, v => (object)v.Value),
        };
        Probe.Log($"SERVE: {n} eps, {steps} steps in {sw.Elapsed.TotalSeconds:F2}s " +
                  $"({(sw.Elapsed.TotalSeconds > 0 ? steps / sw.Elapsed.TotalSeconds : 0):F0} steps/s)");
        Probe.Log($"  outcomes: {string.Join(", ", outcomes.Select(kv => $"{kv.Key}={kv.Value}"))}");
    }

    /// <summary>Minimal parse of {"a":N}; clamped so a bad reply cannot crash the env.</summary>
    private static int ParseAction(string line, int count)
    {
        var i = line.IndexOf("\"a\"", StringComparison.Ordinal);
        if (i < 0) return 0;
        var c = line.IndexOf(':', i);
        if (c < 0) return 0;
        var end = c + 1;
        while (end < line.Length && (char.IsDigit(line[end]) || line[end] == ' ' || line[end] == '-')) end++;
        return int.TryParse(line.Substring(c + 1, end - c - 1).Trim(), out var v)
            ? Math.Clamp(v, 0, count - 1) : 0;
    }
}
